title: JURTA
author: Juri Linkov <juri@jurta.org>
email: juri@jurta.org
description: >-
  JURTA is the home of JURI and TA
logo: /files/jurta_logo.png
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jurta
repository: https://github.com/jurta/jurta.github.io

permalink: /:title # without :output_ext .html

# "ME + ET = MEET"
# collections:
#   meets:
#     output: true
#     permalink: /meets/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "en"
    values:
      lang: "en"
      menu: "menuen"
      menu_title: "Site Map"
  - scope:
      path: "en/emacs"
    values:
      menu_top: "/en/emacs/"
  - scope:
      path: "ru"
    values:
      lang: "ru"
      menu: "menuru"
      menu_title: "Карта сайта"
  - scope:
      path: "ru/tanja"
    values:
      menu: "menuta"
      menu_title: "ТА"
  # - scope:
  #     path: "ru/tanja/meet"
  #   values:
  #     layout: "meet"

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# sass:
#   style: compressed
